### PR TITLE
Better implementation

### PR DESCRIPTION
**Pull request by Aiosa**
I adjusted the hardcoded behavior to support any aspect ratio and rescale images to fit the screen. Screen dimensions change not supported - the game will not adjust (at the current image, the next one will rescale to fit again).

### CODE REVIEW

**Review by petrkucerak — CHANGES_REQUESTED** [review]
@Aiosa 
_FYI: Auto deployment has been set up, so the demo is auto-updated._

It looks like a problem with image coverage. (see screenshot)
Screenshot from 2022-10-03 11-03-05

**Comment by Aiosa** [comment]
Yeah, I knew about this and hoped it will be always small cause the tile width decision should almost fit. But the decision was not so great as I hoped and I did not really test it so for some dimensions it really left out a bigger part which was significant. Added some rounding for robust coverage (since sometimes the image overlapped with 0.0000x and there was one more row/col of 'empty' tiles because of rounding error, that's why the previous implementation did not render last row/col and mostly it worked... somehow). Fixed. Thanks for the feedback.

**Comment by Aiosa** [comment]
Also added back some stuff needed for official repo - did not first want to push to the upstream but then I implemented much more than anticipated..

**Comment by torx-cz** [comment]
@petrkucerak  Your solution doesn't work in Firefox, but solution of @Aiosa  is working perfectly. Just FYI

**Review by petrkucerak — APPROVED** [review]

**Comment by petrkucerak** [comment]
@Aiosa thanks for your contributions and sorry for the late revision.

**Pull request merged**
